name: realtime_innovations
description: Realtime Innovations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
